language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  include:
    # Force testing against LTS versions
    - php: 5.4
      env: SYMFONY_VERSION=2.3.*
    - php: 5.4
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*

before_script:
  - composer self-update
  before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  
install:
  - composer install

script: "phpunit --coverage-text" 